"""Initial tables

Revision ID: 2af8409b0752
Revises: 41c73b1078c4
Create Date: 2024-09-16 17:43:02.946180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2af8409b0752"
down_revision: Union[str, None] = "41c73b1078c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_note_title"), "note", ["title"], unique=True)
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.drop_index(op.f("ix_note_title"), table_name="note")
    # ### end Alembic commands ###
