"""Initial tables

Revision ID: 41c73b1078c4
Revises: 26f80c17e831
Create Date: 2024-09-16 02:47:03.446395

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41c73b1078c4"
down_revision: Union[str, None] = "26f80c17e831"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("note", sa.Column("user_fk", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "note", "user", ["user_fk"], ["id"], ondelete="Cascade")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "note", type_="foreignkey")
    op.drop_column("note", "user_fk")
    # ### end Alembic commands ###
