"""Initial tables

Revision ID: 510e8674f90b
Revises: 2af8409b0752
Create Date: 2024-09-17 03:18:04.374818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "510e8674f90b"
down_revision: Union[str, None] = "2af8409b0752"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_note_title", table_name="note")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_note_title", "note", ["title"], unique=True)
    # ### end Alembic commands ###
