"""Initial tables

Revision ID: 7956e8b032b1
Revises: 510e8674f90b
Create Date: 2024-09-21 23:58:17.854837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7956e8b032b1'
down_revision: Union[str, None] = '510e8674f90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('content', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'content')
    # ### end Alembic commands ###
