services:

  redis:
    image: redis:latest

    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .redis_env